version: '2.4'

services:
  mariadb:
    #build:
    #  context: ./
    #  dockerfile: alpine.armhf.10_4.Dockerfile
    image: austinyhc/alpine-mariadb:armv7
    #container_name: mariadb
    restart: unless-stopped
    volumes:
      - /var/lib/mysql:/var/lib/mysql:rw
      - /run/mysqld:/run/mysqld:rw
      #- mariadb-data:/var/lib/mysql:rw
      #- ./mariadb:/var/lib/mysql:rw
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Taipei
      MYSQL_ROOT_PASSWORD: 1234eszxcv
      MYSQL_DATABASE: mysql
      MYSQL_USER: austin
      MYSQL_PASSWORD: 1234eszxcv
    ports:
      - 3306:3306
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      #start_period: 30s
    networks:
      net-db:
        aliases:
         - mysql
         #- mariadb
         - db

networks:
  net-db:
    name: net-db
