FROM python:3.9.4-alpine

LABEL maintainer="Austin Chen <austin.yhc@gmail.com>"

RUN apk add --no-cache mariadb-connector-c-dev
RUN apk add --no-cache --virtual .build-deps gcc build-base libc-dev make \
        && \
    pip install --no-cache-dir \
        pip \
        fastapi \
        uvicorn[standard] \
        gunicorn \
        mysqlclient \
        sqlalchemy \
        python-multipart \
        pyyaml \
        ujson \
        "pydantic>=1.2.0,<2.0.0" \
        inflection \
        && \
    apk del .build-deps gcc build-base libc-dev make

COPY sh/start.sh /start.sh
COPY gunicorn_conf.py /gunicorn_conf.py
COPY sh/start-reload.sh /start-reload.sh
RUN chmod +x /start.sh && chmod +x /start-reload.sh

EXPOSE 80

# Run the start script, it will check for an /app/prestart.sh script (e.g. for migrations)
# And then will start Gunicorn with Uvicorn
CMD ["/start.sh"]
